Books/urls.py
from django.contrib import admin
from django.urls import path
from Books import views

app_name="Books"

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('',views.home,name="home"),
    path('viewbooks',views.viewbooks,name="viewbooks"),
    path('addbooks',views.addbooks,name="addbooks"),
    path('viewbookdetails/<int:p>   ',views.viewbookdetails,name="viewbookdetails"),
    path('delete/<int:p>',views.delete,name="delete"),
    path('edit/<int:p>',views.edit,name='edit'),
]

Library/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Books.urls')),
    path('readers/',include('Reader.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Reader/urls.py
from django.contrib import admin
from django.urls import path
from Reader import views

app_name="Reader"

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('',views.register,name="register"),
    path('login',views.user_login,name="login"),
    path('logout',views.user_logout,name="logout"),
]

Books/models.py
from django.db import models

# # # Create your models here.
class Book(models.Model):
    title=models.CharField(max_length=20)
    author =models.CharField(max_length=20)
    price=models.IntegerField()
    pages=models.IntegerField()
    languages=models.CharField(max_length=20)
    cover=models.ImageField(upload_to='cover')
    pdf=models.FileField(upload_to='pdf')


    def __str__(self):
        return self.title
    def __str__(self):
        return self.author # only string commads are returned

Reader/models.py
from django.db import models

# Create your models here.
class Reader_model(models.Model):
    name=models.CharField(max_length=20)
    age=models.IntegerField( default=0)
    place=models.CharField(max_length=20,default=" ")
    gender=models.CharField(max_length=10)
    

Books/views.py
from django.shortcuts import render,redirect
from Books.models import Book
from django.contrib.auth.decorators import login_required

# Create your views here.

def home(request):
    return render(request,"home.html")

@login_required
def viewbooks(request):

    # k=modelname.objects.all()

    k=Book.objects.all() # reads all the records from the book table
    context={'book':k}  # sends data from view function to html page
    return render(request,"viewbooks.html",context)

@login_required
def addbooks(request):
    if(request.method=="POST"):
        t=request.POST['t']
        a=request.POST['a']
        pr=request.POST['pr']
        pa=request.POST['pa']
        l=request.POST['l']
        c=request.FILES['c']
        p=request.FILES['p']

        b=Book.objects.create(title=t,author=a,price=pr,pages=pa,languages=l,cover=c,pdf=p)
        b.save()
        # return redirect('addbooks')
        return viewbooks(request)
    return render(request,"addbooks.html")

@login_required
def viewbookdetails(request,p):
    print(p)
    k=Book.objects.get(id=p)  #reads aparticular
    # Need to read details of a particular book
    context={'book':k}
    return render(request,'viewbookdetails.html',context)

@login_required
def delete(request,p):
    k=Book.objects.get(id=p)
    k.delete()
    return redirect('Books:viewbooks')

@login_required
def edit(request,p):
    k=Book.objects.get(id=p)
    if(request.method=="POST"):
        k.title=request.POST['t']
        k.author=request.POST['a']
        k.price=request.POST['pr']
        k.pages=request.POST['pa']
        k.languages=request.POST['l']
        
        if(request.FILES.get('c')==None):
            k.save()
        else:
            k.cover=request.FILES.get('c')

        if(request.FILES.get('p')==None):
            k.save()
        else:
            k.cover=request.FILES.get('p')
        k.save()
        return redirect('Books:viewbooks')
    context={'book':k}
    return render(request,'edit.html',context)

Reader/views.py
from django.shortcuts import render,redirect
from Reader.models import Reader_model
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required

# Create your views here.
def register(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p=request.POST['p']
        cp=request.POST['cp']
        f=request.POST['f']
        l=request.POST['l']
        e=request.POST['e']

        if(p==cp):
            u=User.objects.create_user(username=u,password=p,email=e,first_name=f,last_name=l)
            u.save()
            return redirect ('Books:home')
        else:
            return HttpResponse('Passwords are not valid')
    return render(request,'register.html')

def user_login(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p=request.POST['p']
        user=authenticate(username=u,password=p)

        if user: #if matching user exist
            login(request,user)
            return redirect ('Books:home')
        else: #if no matching user
            return HttpResponse ("invalid Credentials")
    return render(request,"login.html")
@login_required
def user_logout(request):
    logout(request)
    return redirect('Reader:login')

templates/addbooks.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form action="" method="POST" enctype="multipart/form-data">
 {% csrf_token %}
    <h2>Add books to the cart</h2>
  <div class="row g-3 align-items-center">
  <div class="col-auto">
    <label  class="col-form-label">Title </label>
  </div>
  <div class="col-auto">
    <input type="text"  class="form-control "  placeholder="Title" name="t">
  </div>
  </div>
  <br>

  <div class="row g-3 align-items-center">
    <div class="col-auto">
      <label  class="col-form-label">Author</label>
    </div>
    <div class="col-auto">
      <input type="text" class="form-control" name="a"  placeholder="Author">
    </div>
    </div>
    <br>

  <div class="row g-3 align-items-center">
    <div class="col-auto">
        <label  class="col-form-label">Price</label>
    </div>
    <div class="col-auto">
          <input type="number"  class="form-control"  name="pr">
    </div>
   </div>
<br>
<div class="row g-3 align-items-center">
    <div class="col-auto">
      <label for="" class="col-form-label">Pages</label>
    </div>
    <div class="col-auto">
      <input type="number"  class="form-control"  name="pa">
    </div>
    </div>
<br>
<div class="row g-3 align-items-center">
    <div class="col-auto">
      <label for="" class="col-form-label">Language</label>
    </div>
    <div class="col-auto">
      <input type="text"  class="form-control"  name="l">
    </div>
    </div>
<br>
<div class="row g-3 align-items-center">
  <div class="col-auto">
    <label for="" class="col-form-label">Cover</label>
   
  </div>
  <div class="col-auto">
    <input type="file"  class="form-control" name="c">
  </div>
  </div>
<br>
<div class="row g-3 align-items-center">
  <div class="col-auto">
    <label for="" class="col-form-label">pdf</label>
   
  </div>
  <div class="col-auto">
    <input type="file"  class="form-control" name="p">
  </div>
  </div>

  

  <button type="submit" class="btn btn-primary">AddBook</button>
  
</form>  

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-secondary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Library</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
    
              <li class="nav-item">
                <a class="nav-link active " aria-current="page" href="{% url 'Books:home' %}">Home</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'Books:viewbooks' %}">ViewBooks</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'Books:addbooks' %}">AddBooks</a>
              </li>
              <li class="nav-item"></li>
              <a class="nav-link active" aria-current="page" href="{% url 'Reader:logout' %}">Logout</a>
            </li>
              {% else %}
              <li class="nav-item"></li>
                <a class="nav-link active" aria-current="page" href="{% url 'Reader:register' %}">Register</a>
              </li>
              <li class="nav-item"></li>
                <a class="nav-link active" aria-current="page" href="{% url 'Reader:login' %}">Login</a>
              </li>
              
    
            {% endif %}
                      
            </div>
        </div>
      </nav>
    {% block content %}
       Welcome to Library
    {% endblock %}
    
</body>
</html>

templates/edit.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form action="" method="POST" enctype="multipart/form-data">
 {% csrf_token %}
    <h2>Edit book details</h2>
  <div class="row g-3 align-items-center">
  <div class="col-auto">
    <label  class="col-form-label">Title    </label>
  </div>
  <div class="col-auto">
    <input type="text"  class="form-control" value="{{book.title}}"  placeholder="Title" name="t">
  </div>
  </div>
  <br>

  <div class="row g-3 align-items-center">
    <div class="col-auto">
      <label  class="col-form-label">Author</label>
    </div>
    <div class="col-auto">
      <input type="text" class="form-control" name="a" value="{{book.author}}" placeholder="Author">
    </div>
    </div>
    <br>

  <div class="row g-3 align-items-center">
    <div class="col-auto">
        <label  class="col-form-label">Price</label>
    </div>
    <div class="col-auto">
          <input type="number"  class="form-control" value="{{book.price}}" name="pr">
    </div>
   </div>
<br>
<div class="row g-3 align-items-center">
    <div class="col-auto">
      <label for="" class="col-form-label">Pages</label>
    </div>
    <div class="col-auto">
      <input type="number"  class="form-control" value="{{book.pages}}"  name="pa">
    </div>
    </div>
<br>
<div class="row g-3 align-items-center">
    <div class="col-auto">
      <label for="" class="col-form-label">Language</label>
    </div>
    <div class="col-auto">
      <input type="text"  class="form-control" value="language" name="l">
    </div>
    </div>
<br>
<div class="row g-3 align-items-center">
  <div class="col-auto">
    <label for="" class="col-form-label">Cover</label>
    <img src="{{book.cover.url}}" alt="" height="100px" width="100px">
    <input type="file"  class="form-control" name="c">
  </div>
  </div>
<br>
<div class="row g-3 align-items-center">
  <div class="col-auto">
    <label for="" class="col-form-label">pdf</label>
    <a href="{{book.pdf.url}}">{{book.pdf}}</a>
  </div>
  <div class="col-auto">
    <input type="file"  class="form-control" name="p">
  </div>
  </div>

  

  <button type="submit" class="btn btn-primary">Edit</button>
  
</form>  

{% endblock %}

templates/home.html
<!DOCTYPE html>
{% extends 'base.html'%}
{% load static %}

{% block content %}

<H2>Welcome to Readers Club</H2>

{% endblock %}   

templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h2> Login ......</h2>
    <div class="container px-2 mb-5">
        <form action="" method="POST">
            {% csrf_token %}
    
        <div class="col">
          <label for="username" class="form-label">User Name:</label>
          <input type="text" class="form-control" placeholder="User name" name="u">
        </div>
        <div class="col">
            <label for="inputPassword4" class="form-label">Password:</label>
              <input type="password" class="form-control" placeholder="password" name="p">
        </div>
        <label for="">Submit</label>
        <input type="submit">
        </form>
    </div>

{% endblock %}

templates/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h2>Welcome to registration page</h2>

<div class="container px-2 mb-5">
<form action="" method="POST">
    {% csrf_token %}
    
        <div class="col">
          <label for="username" class="form-label">User Name:</label>
          <input type="text" class="form-control" placeholder="User name" name="u">
        </div>
        <div class="col">
        <label for="inputPassword4" class="form-label">Password:</label>
          <input type="password" class="form-control" placeholder="password" name="p">
        </div>
        <div class="col">
        <label for="inputPassword4" class="form-label">Confirm Password:</label>
        <input type="password" class="form-control" placeholder="password" name="cp">
        </div>

        <div class="col">
            <label for="fname" class="form-label">First Name:</label>
          <input type="text" class="form-control" placeholder="First name" name="f">
        </div>
        <div class="col">
            <label for="lname" class="form-label">Last Name:</label>
          <input type="text" class="form-control" placeholder="Last name" name="l">
        </div>
        <div class="col">
            <label for="email" class="form-label">Email :</label>
            <input type="email" class="form-control" placeholder="email" name="e">
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>

</div>
</form>
{% endblock %}

templates/viewbookdetails.html
<!DOCTYPE html>
{% extends 'base.html'%}
{% load static %}

{% block content %}

<H5>here data of a specific book need to be dispalyed</H5>

<div class="card mb-3 mt-5 mx-auto" style="max-width: 540px;">
    <div class="row g-0">
      <div class="col-md-4">
        <img src="{{book.cover.url}}" class="p-4" style="height: 100%;width: 100%;" alt="...">
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h3 class="card-title">{{book.title}}</h3>
          <h5>Author:{{book.author}}</h5>
          <h5>Language:{{book.languages}}</h5>
          <h5>Price:{{book.price}}</h5>
          <br>
          <br>
          <a href="" class="btn btn-danger">Download</a>

        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}   

templates/viewbooks.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h2>View Books</h2>
    <!-- {{book}}  -->
    <table class="table table-bordered border border-1 border-primary">
        <tr>
            <th>Cover</th>
            <th>Title</th>
            <th>Author</th>
            <th>Price</th>
            <th>Pages</th>
            <th>Language</th> 
            <th>pdf</th>
            <th>View</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        {% for i in book %} 
        <!-- # to itrate data from admin-table -->
        <tr>
            <td><img src="{{i.cover.url}}" alt="" height="100px" width="100px"></td>
            <td>{{i.title}}</td>
            <td>{{i.author}}</td>
            <td>{{i.price}}</td>
            <td>{{i.pages}}</td> 
            <td>{{i.languages}}</td>
            <td><a href="{{i.pdf.url}}">download</a></td>
            <td><a href="{% url 'Books:viewbookdetails' i.id %}" class="btn btn-danger">View</a></td>
            <td><a href="{% url 'Books:edit' i.id %}" class="btn btn-danger">Edit</a></td>
            <td><a href="{% url 'Books:delete' i.id %}" class="btn btn-danger">Delete</a></td>  
        </tr> 
        {% endfor %}
     </table>
  
     <!-- <ol>
        {% for i in book %}
        <li>Book Details </li>

        <ul> 
            <li>Title: {{i.title}}</li>
            <li>Author: {{i.author}}</li>
            <li>Price: {{i.price}}</li>
            <li>language:{{i.language}}</li>
            <li>cover:{{i.cover.url}}</li>
            <li>pdf:{{i.pdf.url}}</li>
        </ul>
        {% endfor %}
        
     </ol>
{% endblock %} --> 